export const ADD_EMOJI_REQUEST = 'ADD_EMOJI_REQUEST'
export const ADD_EMOJI_SUCCESS = 'ADD_EMOJI_SUCCESS'
export const ADD_EMOJI_FAIL = 'ADD_EMOJI_FAIL'
export const GET_EMOJI = 'GET_EMOJI'

export const SHOW_ALL_TEXT_REQUEST = 'SHOW_ALL_TEXT_REQUEST'
export const SHOW_ALL_TEXT_SUCCESS = 'SHOW_ALL_TEXT_SUCCESS'
export const SHOW_ALL_TEXT_FAIL = 'SHOW_ALL_TEXT_FAIL'

export const SAVE_MESSAGE_REQUEST = 'SAVE_MESSAGE_REQUEST'
export const SAVE_MESSAGE_SUCCESS = 'SAVE_MESSAGE_SUCCESS'
export const SAVE_MESSAGE_FAIL = 'SAVE_MESSAGE_FAIL'
